language: python
python:
  - "3.8"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - HA_VERSION=$(<.HA_VERSION)
install:
  - python3 -m pip install homeassistant==${HA_VERSION}
script:
  - hass -c . --script check_config
